networks:
  traefik:
    external: true

services:
  languagetool:
    container_name: languagetool
    image: ghcr.io/batinicaz/languagetool:1.2.6@sha256:7a44cd75ceed96626d7b7dd477369f4bb0e6139840d86d950df95333896d7f7f
    restart: unless-stopped
    read_only: true
    user: "783:783"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    volumes:
      - /opt/data/languagetool/ngrams:/ngrams:ro,z
    environment:
      - LISTEN_PORT=8010
      - JAVA_XMS=512m
      - JAVA_XMX=2g
    networks:
      - traefik
