networks:
  traefik:
    external: true

services:
  languagetool:
    container_name: languagetool
    image: ghcr.io/batinicaz/languagetool:1.2.1@sha256:d0844464673af19fe898c9c178530bbc832bc05ee207680495ede79e17411ce9
    restart: unless-stopped
    read_only: true
    user: "783:783"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    volumes:
      - /opt/data/languagetool/ngrams:/ngrams:ro,z
    environment:
      - LISTEN_PORT=8010
      - JAVA_XMS=512m
      - JAVA_XMX=2g
    networks:
      - traefik
