networks:
  traefik:
    external: true

services:
  languagetool:
    container_name: languagetool
    image: ghcr.io/batinicaz/languagetool:1.3.0@sha256:3936050f44d347125e9780d2ee288c0167e8e37f07369cc8d8a78d7ed7ecffae
    restart: unless-stopped
    read_only: true
    user: "783:783"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    volumes:
      - /opt/data/languagetool/ngrams:/ngrams:ro,z
    environment:
      - LISTEN_PORT=8010
      - JAVA_XMS=512m
      - JAVA_XMX=2g
    networks:
      - traefik
