networks:
  traefik:
    external: true
  podcasts:
    external: true

services:
  podly:
    container_name: podly
    image: ghcr.io/podly-pure-podcasts/podly-pure-podcasts:2.5.0-lite-arm64@sha256:ae09de0ae24abd161646ce0edc22a04425d21f46f5a1d17c781e0b544e88c1d8
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    volumes:
      - /opt/data/podly/instance:/app/src/instance:z
    env_file:
      - /opt/secrets/podly.env
    environment:
      TZ: Europe/London
      REQUIRE_AUTH: "true"
    networks:
      - traefik
      - podcasts

  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:2.35.1@sha256:1eef6716183c52abafe5405e7d6be8390248ecd59c7488c44af871757ac8fc4d
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    volumes:
      - /opt/data/podcasts:/podly-source:ro,z
      - /opt/data/audiobookshelf/podly-destination:/podly-destination:z
      - /opt/data/audiobookshelf/config:/config:z
      - /opt/data/audiobookshelf/metadata:/metadata:z
    environment:
      TZ: Europe/London
      PORT: "8000"
      METADATA_PATH: /metadata
    networks:
      - traefik
      - podcasts

  get_iplayer:
    container_name: get_iplayer
    image: ghcr.io/thespad/get_iplayer:3.23@sha256:f7a2dd5b1ff203db0061e25a6d5aceef56619f8e786d79b4a1ab172819de628a
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true
    ports:
      - 1935:1935
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /opt/data/get_iplayer/config:/config:z
      - /opt/data/podcasts:/podcasts:z
      - ./get_iplayer-init:/custom-cont-init.d:ro,z
    environment:
      TZ: Europe/London
      PUID: 1000
      PGID: 1000
      INCLUDERADIO: "true"
    networks:
      - podcasts
