name: Update Terraform Docs
on:
  push:
    branches:
      - "renovate/**"
permissions:
  contents: read
jobs:
  terraform-docs:
    uses: batinicaz/gha/.github/workflows/terraform-docs.yml@v1
    with:
      working_directory: terraform
      output_file: ../README.md
      update_lock_file: true
      git_commit_message: "chore: update terraform docs and lock file"
    secrets:
      DOCUMENTATION_APP_ID: ${{ secrets.DOCUMENTATION_APP_ID }}
      DOCUMENTATION_PRIVATE_KEY: ${{ secrets.DOCUMENTATION_PRIVATE_KEY }}
